package br.edu.unifor.timexnetwork.test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import br.edu.unifor.timexnetwork.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
